Comment out step to autoformat code

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,13 +43,13 @@ jobs:
       - name: Test with pytest
         run: poetry run pytest -v -m "not slow_test" -m "not plots" --cov . --cov-report xml:coverage-reports/coverage-hydrolib.xml --junitxml=xunit-reports/xunit-result-hydrolib.xml
 
-      - name: Autoformat code if the check fails
-        if: ${{ (matrix.os == 'ubuntu-latest') && (matrix.python-version == 3.8) }}
-        run: |
-          poetry run isort .
-          poetry run black .
-          git config --global user.name '${{ github.actor }}'
-          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
-          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
-          git checkout $GITHUB_HEAD_REF
-          git commit -am "autoformat: isort & black" && git push || true
+      #- name: Autoformat code if the check fails
+      #  if: ${{ (matrix.os == 'ubuntu-latest') && (matrix.python-version == 3.8) }}
+      #  run: |
+      #    poetry run isort .
+      #    poetry run black .
+      #    git config --global user.name '${{ github.actor }}'
+      #    git config --global user.email '${{ github.actor }}@users.noreply.github.com'
+      #    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
+      #    git checkout $GITHUB_HEAD_REF
+      #    git commit -am "autoformat: isort & black" && git push || true
