chore: Fix CI by replacing conda with poetry and add init files to dhydamo modules (#143)
Note: black autoformatting has been disabled for the time being, awaiting several major feature branch merges.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,50 +8,48 @@ jobs:
       fail-fast: false
       matrix:
         python-version: [3.8, 3.9]
-        os: [ubuntu-18.04, macos-latest, windows-latest]
+        os: [ubuntu-latest, macos-latest, windows-latest]
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
-      - name: Cache conda
-        uses: actions/cache@v2
-        env:
-          # Increase this value to reset cache if etc/example-environment.yml has not changed
-          CACHE_NUMBER: 0
+      - name: Set up Python
+        uses: actions/setup-python@v1
         with:
-          path: ~/conda_pkgs_dir
-          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
-            hashFiles('environment.yaml') }}
-
-      - uses: conda-incubator/setup-miniconda@v2
-        with:
-          activate-environment: hydrolib
           python-version: ${{ matrix.python-version }}
-          environment-file: environment.yaml
-          channels: conda-forge,defaults
-          channel-priority: true
-          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
-          mamba-version: "*"
 
-      - name: Install dev tools
-        shell: bash -l {0}
+      - name: Run image
+        uses: abatilo/actions-poetry@v2.0.0
+        with:
+          poetry-version: 1.3.1
+      - name: Cache Poetry virtualenv
+        uses: actions/cache@v3
+        id: cache
+        with:
+          path: ~/.virtualenvs
+          key: venv-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
+
+      - name: Set Poetry config
         run: |
-          conda install isort black pytest pytest-cov
+          poetry config virtualenvs.in-project false
+          poetry config virtualenvs.path ~/.virtualenvs
+
+      - name: Install Dependencies
+        run: poetry install
+        if: steps.cache.outputs.cache-hit != 'true'
 
       - name: Test with pytest
-        shell: bash -l {0}
-        run: pytest -v -m "not slow_test" -m "not plots" --cov . --cov-report xml:coverage-reports/coverage-hydrolib.xml --junitxml=xunit-reports/xunit-result-hydrolib.xml
+        run: poetry run pytest -v -m "not slow_test" -m "not plots" --cov . --cov-report xml:coverage-reports/coverage-hydrolib.xml --junitxml=xunit-reports/xunit-result-hydrolib.xml
 
-      - name: Autoformat code if the check fails
-        if: ${{ (matrix.os == 'ubuntu-18.04') && (matrix.python-version == 3.8) }}
-        shell: bash -l {0}
-        run: |
-          isort .
-          black .
-          git config --global user.name '${{ github.actor }}'
-          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
-          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
-          git checkout $GITHUB_HEAD_REF
-          git commit -am "autoformat: isort & black" && git push || true
+      #- name: Autoformat code if the check fails
+      #  if: ${{ (matrix.os == 'ubuntu-latest') && (matrix.python-version == 3.8) }}
+      #  run: |
+      #    poetry run isort .
+      #    poetry run black .
+      #    git config --global user.name '${{ github.actor }}'
+      #    git config --global user.email '${{ github.actor }}@users.noreply.github.com'
+      #    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
+      #    git checkout $GITHUB_HEAD_REF
+      #    git commit -am "autoformat: isort & black" && git push || true
